/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.1.0.0 (NJsonSchema v9.13.28.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class Client {
	private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
	private baseUrl: string;
	protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

	constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
		this.http = http ? http : <any>window;
		this.baseUrl = baseUrl ? baseUrl : "";
	}

	/**
	 * @return Success
	 */
	getBoard(): Promise<StatusDto[]> {
		let url_ = this.baseUrl + "/api/Data/GetBoard";
		url_ = url_.replace(/[?&]$/, "");

		let options_ = <RequestInit>{
			method: "GET",
			headers: {
				"Accept": "application/json"
			}
		};

		return this.http.fetch(url_, options_).then((_response: Response) => {
			return this.processGetBoard(_response);
		});
	}

	protected processGetBoard(response: Response): Promise<StatusDto[]> {
		const status = response.status;
		let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
		if (status === 200) {
			return response.text().then((_responseText) => {
				let result200: any = null;
				let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
				if (resultData200 && resultData200.constructor === Array) {
					result200 = [] as any;
					for (let item of resultData200)
						result200!.push(StatusDto.fromJS(item));
				}
				return result200;
			});
		} else if (status !== 200 && status !== 204) {
			return response.text().then((_responseText) => {
				return throwException("An unexpected server error occurred.", status, _responseText, _headers);
			});
		}
		return Promise.resolve<StatusDto[]>(<any>null);
	}
}

export class StatusDto implements IStatusDto {
	id?: string | undefined;
	title?: string | undefined;
	tasks?: TaskDto[] | undefined;

	constructor(data?: IStatusDto) {
		if (data) {
			for (var property in data) {
				if (data.hasOwnProperty(property))
					(<any>this)[property] = (<any>data)[property];
			}
		}
	}

	init(data?: any) {
		if (data) {
			this.id = data["id"];
			this.title = data["title"];
			if (data["tasks"] && data["tasks"].constructor === Array) {
				this.tasks = [] as any;
				for (let item of data["tasks"])
					this.tasks!.push(TaskDto.fromJS(item));
			}
		}
	}

	static fromJS(data: any): StatusDto {
		data = typeof data === 'object' ? data : {};
		let result = new StatusDto();
		result.init(data);
		return result;
	}

	toJSON(data?: any) {
		data = typeof data === 'object' ? data : {};
		data["id"] = this.id;
		data["title"] = this.title;
		if (this.tasks && this.tasks.constructor === Array) {
			data["tasks"] = [];
			for (let item of this.tasks)
				data["tasks"].push(item.toJSON());
		}
		return data;
	}
}

export interface IStatusDto {
	id?: string | undefined;
	title?: string | undefined;
	tasks?: TaskDto[] | undefined;
}

export class TaskDto implements ITaskDto {
	id?: string | undefined;
	title?: string | undefined;

	constructor(data?: ITaskDto) {
		if (data) {
			for (var property in data) {
				if (data.hasOwnProperty(property))
					(<any>this)[property] = (<any>data)[property];
			}
		}
	}

	init(data?: any) {
		if (data) {
			this.id = data["id"];
			this.title = data["title"];
		}
	}

	static fromJS(data: any): TaskDto {
		data = typeof data === 'object' ? data : {};
		let result = new TaskDto();
		result.init(data);
		return result;
	}

	toJSON(data?: any) {
		data = typeof data === 'object' ? data : {};
		data["id"] = this.id;
		data["title"] = this.title;
		return data;
	}
}

export interface ITaskDto {
	id?: string | undefined;
	title?: string | undefined;
}

export class SwaggerException extends Error {
	message: string;
	status: number;
	response: string;
	headers: { [key: string]: any; };
	result: any;

	constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
		super();

		this.message = message;
		this.status = status;
		this.response = response;
		this.headers = headers;
		this.result = result;
	}

	protected isSwaggerException = true;

	static isSwaggerException(obj: any): obj is SwaggerException {
		return obj.isSwaggerException === true;
	}
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
	if (result !== null && result !== undefined)
		throw result;
	else
		throw new SwaggerException(message, status, response, headers, null);
}